name: Build and deploy Node.js app to Azure Web App - RGI

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install and build frontend
        run: |
          cd my-frontend
          npm install
          CI=false npm run build --if-present
          CI=false npm run test --if-present

      - name: Install backend dependencies
        run: |
          cd my-backend
          npm install

      - name: Prepare deployment package
        run: |
          mkdir -p deployment/my-frontend
          mkdir -p deployment/my-backend
          cp -r my-frontend/build/* deployment/my-frontend/
          cp my-frontend/package.json deployment/my-frontend/
          cp -r my-backend/* deployment/my-backend/
          cp my-backend/package.json deployment/my-backend/
          zip -r release.zip deployment

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Display directory structure for debugging
        run: ls -R deployment

      - name: Check files and permissions
        run: |
          find deployment -type f -exec ls -lah {} \;
          find deployment -type d -exec ls -ld {} \;

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'RGI'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: deployment
          slot-name: production
